nan:communication.py 100, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
4319043:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
4320644:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020086723100>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4323444:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200879DE7C0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
